// File: .github/workflows/cr.yml
name: Create CR on PR
on:
  pull_request:
    types: [opened]

jobs:
  create-cr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve
